import { hotjar } from 'react-hotjar'
import { useEffect } from 'react'
export default function Head() {
  useEffect(() => {
    hotjar.initialize(3384548, 6)
  }, [])

  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
