"use client";

import { hotjar } from 'react-hotjar'
import { useEffect } from 'react'
import { initGA } from '@/utils/g-analytics';
import { useRouter } from 'next/router';

export default function Head() {
  const router = useRouter()
  useEffect(() => {
    hotjar.initialize(3384548, 6)
  }, [])


  useEffect(() => {
    initGA()
    GAnalyticsPageView()
    router.events.on('routeChangeComplete', logPageView)
    return () => {
      router.events.off('routeChangeComplete', logPageView)
    }
  }, [])

  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
